<?php
$brands = $this->getBrands();
$featured = $this->getFeaturedBrands();
$media = $this->getImageMediaPath();
?>
<style>
    .brand-char {
        min-width: 300px;
        float: left;
        min-height: 130px;
    }
    ul.brandlist{ list-style: none;}
</style>
<?php /* ?>
  <h3>Featured Brands</h3>
  <div class="featured-brands">
  <?php foreach($featured as $_fbrand):?>

  <span>
  <a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
  <?php if($_fbrand->getLogo()):?>
  <img class="f-barnd-img" src="<?php echo $media.$_fbrand->getLogo() ?>" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>" style="height:100px"/>
  <?php else:?>
  <span class="brand-title">
  <?php echo $_fbrand->getName();?>
  </span>
  <?php endif;?>
  </a>
  </span>
  <?php endforeach;?>
  </div>
  <br />

  <?php */ ?>
<?php
foreach (range('A', 'Z') as $char) :
    ?>
    <?php if (isset($brands[$char])): ?>
        <div class="brand-char">
            <strong> # <?php echo $char; ?></strong>
            <ul class="brandlist">
                <?php foreach ($brands[$char] as $_brand): ?>
                    <li>
                        <a href="<?php echo $this->getUrl('brands/'.$_brand->getUrlKey()); ?>">
                            <?php
                            if ($_brand->getLogo()):
                                ?>
                                <div style="widht:120px;">
                                    <img class="f-barnd-img" src="<?php echo $media . $_brand->getLogo() ?>" title="<?php echo $_brand->getName(); ?>" alt="<?php echo $_brand->getName(); ?>"/>
                                </div>
                            <?php endif; ?>                                        
                            <?php echo $_brand->getName(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endforeach; ?>