<?php
/**
 * @author      Oscprofessionals Team (support@oscprofessionals.com)
 * @copyright   Copyright (c) 2015 Oscprofessionals (http://www.oscprofessionals.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @category    Oscprofessionals
 * @package     Oscprofessionals_Vatexempt
 */

 /**
 * @var $block \Oscprofessionals\Vatexempt\Block\Datajs
 */
?>
<?php
 
$arrayData = [
	"isVatexemptEnabled" => $this->helper('Oscprofessionals\Vatexempt\Helper\Data')->isModuleEnabled(),
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($arrayData);
?>
<script>    
    window.vatexemptConfig = <?php /* @noEscape */ echo $serializedFormData ?>;	
</script>
