<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/*
?>
<div class="home-slider"> 
    <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider.jpg'); ?>"/></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider.jpg'); ?>"/></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider.jpg'); ?>"/></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('images/sliderjpg'); ?>"/></div>
</div>
<script type="text/javascript">
    require(['js/owl.carousel.min'], function () {
        jQuery(document).ready(function () {
            jQuery(".home-slider").owlCarousel({
                navigation: false, // Show next and prev buttons
                slideSpeed: 300,
                singleItem: true,
                autoPlay: true
            });
        });
    });
</script>
<style type="text/css">

    .owl-carousel .owl-wrapper:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }
    /* display none until init */
/*
    .owl-carousel{
        display: none;
        position: relative;
        width: 100%;
        -ms-touch-action: pan-y;
    }
    .owl-carousel .owl-wrapper{
        display: none;
        position: relative;
        -webkit-transform: translate3d(0px, 0px, 0px);
    }
    .owl-carousel .owl-wrapper-outer{
        overflow: hidden;
        position: relative;
        width: 100%;
    }
    .owl-carousel .owl-wrapper-outer.autoHeight{
        -webkit-transition: height 500ms ease-in-out;
        -moz-transition: height 500ms ease-in-out;
        -ms-transition: height 500ms ease-in-out;
        -o-transition: height 500ms ease-in-out;
        transition: height 500ms ease-in-out;
    }

    .owl-carousel .owl-item{
        float: left;
    }
    .owl-controls .owl-page,
    .owl-controls .owl-buttons div{
        cursor: pointer;
    }
    .owl-controls {
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
    }

    /* mouse grab icon *//*
    .grabbing { 
        cursor:url(../images/grabbing.png) 8 8, move;
    }

    /* fix *//*
    .owl-carousel  .owl-wrapper,
    .owl-carousel  .owl-item{
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility:    hidden;
        -ms-backface-visibility:     hidden;
        -webkit-transform: translate3d(0,0,0);
        -moz-transform: translate3d(0,0,0);
        -ms-transform: translate3d(0,0,0);
    }
</style>
    <?php */ ?>
<style type="text/css">
    .home-promo img,  .shipping-info img, .medical-condition img{
        width:100%; max-width:none;
    }
    .magestore-bannerslider-standard {
        width:100% !important;
    }

    .home-promo ul li:nth-child(3n+3)
    {margin-right: 0;}

    @media only screen and (max-width: 1037px) 
    {
        .home-promo ul li, .home-promo ul li:nth-child(3n+3) {
            margin-right: 1.6% }
        .home-promo ul li:nth-child(2n+2) {
            margin-right: 0;
        }
        .home-promo ul li {
            width: 48.8%;
        }
    }
    @media only screen and (max-width: 767px) {
        .cms-index-index .page-header {margin: 0;}
    }
    @media only screen and (max-width: 360px) {
        .home-promo ul li {width: 100%; margin: 0;}
    }
</style>